version: "3.9"

services:
  user_management_db:
    image: postgres:17.2
    container_name: user_management_db
    networks:
      - main
    volumes:
      - user_db_data:/var/lib/postgresql/data
    env_file:
      - ./services/user_management/postgres.env
    ports:
      - "5433:5432"
    restart: always

  notification_system_db:
    image: postgres:17.2
    container_name: notification_system_db
    networks:
      - main
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    env_file:
      - ./services/notification_system/postgres.env
    ports:
      - "5434:5432"
    restart: always

  notification:
    build:
      context: ./services/notification_system
      dockerfile: Dockerfile
    image: notification:1.0
    container_name: notification
    volumes:
      - ./services/notification_system:/app/
      - static:/app/static
      - media:/app/media
    networks:
      - main
    depends_on:
      - notification_system_db
    env_file:
      - ./services/notification_system/.env
    ports:
      - "8002:8000"
      - "50051:50051"
    restart: always

  user_management:
    build:
      context: ./services/user_management
      dockerfile: Dockerfile
    image: user_management:1.0
    container_name: user_management
    volumes:
      - ./services/user_management:/app/
      - static:/app/static
      - media:/app/media
    networks:
      - main
    depends_on:
      - user_management_db
    env_file:
      - ./services/user_management/.env
    ports:
      - "8001:8000"
    restart: always

  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/www/static
      - media:/var/www/media
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main
    depends_on:
      - user_management_db
      - notification_system_db
    restart: always

  redis:
    image: redis:7.4.2
    container_name: redis
    networks:
      - main
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]

volumes:
  notification_db_data:
  user_db_data:
  static:
  media:


networks:
  main:
