# Generated by Django 5.2.4 on 2025-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('keynote', 'Keynote Speaker'), ('guest', 'Guest Speaker'), ('panelist', 'Panelist'), ('host', 'Host'), ('moderator', 'Moderator'), ('other', 'Other')], default='others', max_length=16)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/speaker/')),
                ('socials', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
