# Generated by Django 5.2.4 on 2025-07-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='type',
            field=models.CharField(choices=[('keynote', 'Keynote Speaker'), ('guest', 'Guest Speaker'), ('panelist', 'Panelist'), ('host', 'Host'), ('moderator', 'Moderator'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
