# Generated by Django 5.2.4 on 2025-07-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_speakers_session_access_type'),
        ('speaker', '0002_alter_speaker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaker.speaker')),
            ],
            options={
                'unique_together': {('session', 'speaker')},
            },
        ),
    ]
