# Generated by Django 5.2.4 on 2025-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_organizer'),
        ('speaker', '0003_sessionspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.event'),
        ),
    ]
