# Generated by Django 5.2.4 on 2025-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('invite_only', 'Invite only')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('cover_images', models.ImageField(blank=True, null=True, upload_to='images/events/')),
                ('gallery', models.JSONField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
