# Generated by Django 5.2.4 on 2025-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventguest_eventinvite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventguest',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_event_email'),
        ),
    ]
