# Generated by Django 5.2.4 on 2025-07-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventguest_unique_event_email'),
        ('organizer', '0002_organizermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizer.organizer'),
            preserve_default=False,
        ),
    ]
