# Generated by Django 5.1.4 on 2025-04-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='message',
            new_name='body',
        ),
    ]
