# Generated by Django 5.1.4 on 2025-02-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('full_address', models.TextField()),
                ('postal_code', models.CharField(max_length=16)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
