# Generated by Django 5.1.4 on 2025-03-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('busy', 'Busy')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
