# Generated by Django 5.1.4 on 2025-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_staffuser_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendeeuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
