# Generated by Django 5.2.4 on 2025-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='speakers',
        ),
        migrations.AddField(
            model_name='session',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20),
        ),
    ]
